language: go
go:
  - 1.10.x
# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
before_install:
  - go get github.com/mattn/goveralls
script:
  - $HOME/gopath/bin/goveralls -v -service=travis-ci